"""empty message

Revision ID: 5bfb0844ceaf
Revises: 9a70674bc270
Create Date: 2025-11-25 11:32:09.703097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '5bfb0844ceaf'
down_revision: Union[str, Sequence[str], None] = '9a70674bc270'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conficuenta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('km_rotacion', sa.Integer(), nullable=False),
    sa.Column('tipo_combustible', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('tipo_presion', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('ref_logo', sqlmodel.sql.sqltypes.AutoString(length=400), nullable=False),
    sa.Column('tiempo_app', sa.Integer(), nullable=False),
    sa.Column('tiempo_user', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('iva_sri', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('cliente', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conficuenta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conficuenta_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conficuenta_tipo'), ['tipo'], unique=False)

    op.create_table('tireeventapp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('variable', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('tireeventapp', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tireeventapp_tipo'), ['tipo'], unique=False)

    with op.batch_alter_table('tirehistory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posicion_anterior', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('posicion_nueva', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('motivo_baja', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('tipo_reparacion', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('costo_reparacion', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tirehistory', schema=None) as batch_op:
        batch_op.drop_column('costo_reparacion')
        batch_op.drop_column('tipo_reparacion')
        batch_op.drop_column('motivo_baja')
        batch_op.drop_column('posicion_nueva')
        batch_op.drop_column('posicion_anterior')

    with op.batch_alter_table('tireeventapp', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tireeventapp_tipo'))

    op.drop_table('tireeventapp')
    with op.batch_alter_table('conficuenta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conficuenta_tipo'))
        batch_op.drop_index(batch_op.f('ix_conficuenta_cliente_id'))

    op.drop_table('conficuenta')
    # ### end Alembic commands ###
