"""empty message

Revision ID: 7119fdc0190f
Revises: adbe2cfaf3b1
Create Date: 2025-11-20 17:19:51.502275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '7119fdc0190f'
down_revision: Union[str, Sequence[str], None] = 'adbe2cfaf3b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehiculo', schema=None) as batch_op:
        batch_op.alter_column('capacidad_tanque',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('10'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehiculo', schema=None) as batch_op:
        batch_op.alter_column('capacidad_tanque',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('10'))

    # ### end Alembic commands ###
