"""empty message

Revision ID: 9a70674bc270
Revises: 7119fdc0190f
Create Date: 2025-11-21 15:25:23.306064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9a70674bc270'
down_revision: Union[str, Sequence[str], None] = '7119fdc0190f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehiculoinspection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('odometro', sa.Integer(), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=False),
    sa.Column('estado_general', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('notas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['inspector_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tirehistory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado_visual', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('criticidad', sqlmodel.sql.sqltypes.AutoString(length=10), server_default=sa.text("'OK'"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tirehistory', schema=None) as batch_op:
        batch_op.drop_column('criticidad')
        batch_op.drop_column('estado_visual')

    op.drop_table('vehiculoinspection')
    # ### end Alembic commands ###
