"""empty message

Revision ID: a14fd9c3c2dc
Revises: a5aa65b202f4
Create Date: 2025-11-12 16:16:04.090849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a14fd9c3c2dc'
down_revision: Union[str, Sequence[str], None] = 'a5aa65b202f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tire', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dot', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.alter_column('size',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_tire_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_tire_size'), ['size'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tire', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tire_size'))
        batch_op.drop_index(batch_op.f('ix_tire_brand'))
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('size',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('fecha_creacion')
        batch_op.drop_column('dot')

    # ### end Alembic commands ###
