"""empty message

Revision ID: a5aa65b202f4
Revises: ee96a72b03a0
Create Date: 2025-11-10 16:36:23.907198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a5aa65b202f4'
down_revision: Union[str, Sequence[str], None] = 'ee96a72b03a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventoryadjustment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehiculo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=2), server_default=sa.text("'AC'"), nullable=False))
        batch_op.add_column(sa.Column('creado_por', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehiculo', schema=None) as batch_op:
        batch_op.drop_column('creado_por')
        batch_op.drop_column('estado')

    op.drop_table('inventoryadjustment')
    # ### end Alembic commands ###
