"""empty message

Revision ID: adbe2cfaf3b1
Revises: d6e63cf8625d
Create Date: 2025-11-20 16:29:00.144986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'adbe2cfaf3b1'
down_revision: Union[str, Sequence[str], None] = 'd6e63cf8625d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehiculo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_combustible', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'Diesel'"), nullable=False))
        batch_op.add_column(sa.Column('capacidad_tanque', sa.Integer(), server_default=sa.text('10'), nullable=True))
        batch_op.add_column(sa.Column('medida_tire', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'215/75R17.5'"), nullable=False))
        batch_op.add_column(sa.Column('numero_tire', sa.Integer(), server_default=sa.text('4'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehiculo', schema=None) as batch_op:
        batch_op.drop_column('numero_tire')
        batch_op.drop_column('medida_tire')
        batch_op.drop_column('capacidad_tanque')
        batch_op.drop_column('tipo_combustible')

    # ### end Alembic commands ###
