"""empty message

Revision ID: b32f631b5917
Revises: a14fd9c3c2dc
Create Date: 2025-11-13 18:10:35.497802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b32f631b5917'
down_revision: Union[str, Sequence[str], None] = 'a14fd9c3c2dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tire', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asignado_a_vehiculo', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=2), server_default=sa.text("'AC'"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tire', schema=None) as batch_op:
        batch_op.drop_column('estado')
        batch_op.drop_column('asignado_a_vehiculo')

    # ### end Alembic commands ###
